name: Count tabs

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Count tabs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed" >> report.log 2>&1
            echo "Counted tabs in files: `grep -o "   " $file | wc -l`" >> report.log 2>&1 
          done
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log

